Revert "we only need to sync once in maint mode"
This reverts commit 1eb0ae10785d36e80558dae812e117f9b087c05f.

diff --git a/iabak-helper b/iabak-helper
--- a/iabak-helper
+++ b/iabak-helper
@@ -114,8 +114,6 @@ download () {
 		echo "Download finished, but the backup of this shard is not fully complete."
 		echo "Some files may have failed to download, or all allocated disk space is in use."
 	fi
-
-	syncshard || echo "Warning: failed to sync shard; results of download not known to be recoded on the server."
 }
 
 find_insufficient_copies () {
@@ -245,6 +243,7 @@ maint () {
 	fsckme
 
 	if [ ! "$CRONJOB" ]; then
+		syncshard || (echo "Error: failed to sync shard in maintenance mode"; exit 1)
 		periodicsync &
 		if rundownloadfiles; then
 			echo ""
@@ -360,6 +359,8 @@ handleshard () {
 			echo "unknown state $state for shard $shard" >&2
 		;;
 	esac
+
+	syncshard || echo "Warning: failed to sync shard; results of download not known to be recoded on the server."
 }
 
 # Order with newest checked out shards first.
