only update fsck.log weekly
The cron job runs more often than weekly, in order to find a time when
the disk is plugged in, computer is on, etc.

But, we only expire clients after 1 month of no fscks. So, actually
updating the fsck.log daily is excessive. Causes git-annex branch to
grow, and causes load on the server to sync it.

This uses a timestamp to only run the fast fsck if it's been a week since the
last one. Otherwise, the cron job avoids doing anything.

diff --git a/iabak-helper b/iabak-helper
--- a/iabak-helper
+++ b/iabak-helper
@@ -222,12 +222,22 @@ fastfsck () {
 	# The point of this is just to report that the repository still
 	# exists, to prevent it from expiring.
 	# Even a fsck --fast --in here is a litte too slow to run
-	# frequently.
+	# frequently, so fsck an empty directory.
 	if [ ! -d .empty ]; then
 		mkdir .empty
 	fi
-	${GITANNEX} fsck --fast .empty --quiet >/dev/null 2>/dev/null || true
-	syncshard || echo "Warning: failed to sync this shard; fsck results not recorded on server"
+	# Only run the fast fsck once per week, to avoid unncessary churn
+	# in the git-annex branch. Look at the timestamp of the .empty
+	# directory.
+	if [ -n "$(find .empty -mtime 7)" ]; then
+		${GITANNEX} fsck --fast .empty --quiet >/dev/null 2>/dev/null || true
+		if syncshard; then
+			touch .empty
+		else
+			echo "Warning: failed to sync this shard; fsck results not recorded on server"
+			# .empty not touched, so will try to sync next time
+		fi
+	fi
 }
 
 maint () {
